FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./package.json
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
ARG AUTH_URL
ARG AUTH_SECRET
ARG API_INTERNAL_URL
ARG NEXT_PUBLIC_API_URL
ENV AUTH_URL=$AUTH_URL
ENV AUTH_SECRET=$AUTH_SECRET
ENV API_INTERNAL_URL=$API_INTERNAL_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
EXPOSE 3000
CMD ["npm", "run", "start"]
